# config.yml
cufflinks: "/home/hayer/itmat/benchmark_quantifiers/tools/cufflinks-2.2.1.Linux_x86_64/cufflinks"
annotation_gtf: "/project/itmatlab/for_katharina/greg_new/annotation/simulator_config_geneinfo_mm9-ensembl-stdchr_GTF.gtf"
samtools: "samtools"
gatk: "/Users/hayer/Documents/GATK/dist/GenomeAnalysisTK.jar"
annotation_file: "something"
index_fa: "/Users/hayer/Downloads/indexes/ucsc.hg19.fasta"
index_vcf: "/Users/hayer/Downloads/indexes/dbsnp_132.hg19.vcf"
picard_tools: "/Users/hayer/Downloads/picard_tools-1.5/"
