# config.yml
annotation_gtf: "/project/itmatlab/for_katharina/sim_new/annotation/simulator_config_geneinfo_mm9-ensembl-stdchr_GTF.gtf"
# Bowtie
bowtie_index: "/home/hayer/itmat/benchmark_quantifiers/index/transcripts_offrate_1"
bowtie: "/home/hayer/itmat/benchmark_quantifiers/tools/bowtie-1.1.2/bowtie"
cufflinks: "/home/hayer/itmat/benchmark_quantifiers/tools/cufflinks-2.2.1.Linux_x86_64/cufflinks"
express: "/home/hayer/itmat/benchmark_quantifiers/tools/express-1.5.1-linux_x86_64/express"
genome_fa: "/home/hayer/itmat/benchmark_quantifiers/index/mm9_ucsc_all_numbered_chr.fa"
gmap: "/home/hayer/tools/gmap-current/bin/gmap"
ireckon_ucsc: "/project/itmatlab/for_katharina/sim_new/annotation/mm9_ensebl_ucsc_format_filtered.txt"
ireckon: "/home/hayer/itmat/benchmark_quantifiers/tools/IReckon-1.0.8.jar"
isoem_cluster: "/home/hayer/itmat/benchmark_quantifiers/index/cluster_ISOEM_knownToEnsembl.txt"
isoem: "/home/hayer/itmat/benchmark_quantifiers/tools/isoem-1.1.3/bin/isoem"
isolasso_ref: "/project/itmatlab/for_katharina/sim_new/annotation/ensembl_mm9_nov_2015_filtered.bed_SORTED "
isolasso: "/home/hayer/itmat/benchmark_quantifiers/tools/isolasso/bin/runlasso.py"
kallisto_index: "/home/hayer/itmat/benchmark_quantifiers/index/transcripts_kallisto"
kallisto: "/home/hayer/itmat/benchmark_quantifiers/tools/kallisto_linux-v0.42.3/kallisto"
pennseq: "/home/hayer/itmat/benchmark_quantifiers/tools/PennSeq/pennseq/pennseq.pl"
# Index just the base; will need mm9_ensembl_ucsc_format_filtered_pennseq_chrX, mm9_ensembl_ucsc_format_filtered_pennseq_chrY, ...
pennseq_index: "/home/hayer/itmat/benchmark_quantifiers/tools/PennSeq/mm9_ensembl_ucsc_format_filtered_pennseq"
rsem_index: "/home/hayer/itmat/benchmark_quantifiers/index/RSEM_mm9_ucsc_all_numbered_chr_transcripts_INDEX"
rsem: "/home/hayer/itmat/benchmark_quantifiers/tools/RSEM-1.2.23/rsem-calculate-expression"
sailfish_index: "/home/hayer/itmat/benchmark_quantifiers/index/sailfish_transcripts_index"
sailfish: "/home/hayer/itmat/benchmark_quantifiers/tools/SailfishBeta-0.8.0_DebianSqueeze/bin/sailfish"
samtools: "/home/hayer/itmat/bp2/tools/samtools-0.1.19/samtools"
stringtie: "/home/hayer/itmat/benchmark_quantifiers/tools/stringtie-1.1.2.Linux_x86_64/stringtie"
transcripts_fa: "/home/hayer/itmat/benchmark_quantifiers/index/transcripts.fa"
trinity_grid: "/home/hayer/itmat/benchmark_quantifiers/tools/trinityrnaseq-2.1.1/lsf_conf_file.txt"
trinity_quant: "/home/hayer/itmat/benchmark_quantifiers/tools/trinityrnaseq-2.1.1/util/align_and_estimate_abundance.pl"
trinity: "/home/hayer/itmat/benchmark_quantifiers/tools/trinityrnaseq-2.1.1/Trinity"
