# config.yml
cufflinks: "/home/hayer/itmat/benchmark_quantifiers/tools/cufflinks-2.2.1.Linux_x86_64/cufflinks"
annotation_gtf: "/project/itmatlab/for_katharina/greg_new/annotation/simulator_config_geneinfo_mm9-ensembl-stdchr_GTF.gtf"
transcripts_fa: "/home/hayer/itmat/benchmark_quantifiers/index/transcripts.fa"
genome_fa: "/home/hayer/itmat/benchmark_quantifiers/index/mm9_ucsc_all_numbered_chr.fa"
# Bowtie
bowtie: "/home/hayer/itmat/benchmark_quantifiers/tools/bowtie-1.1.2/bowtie"
bowtie_index: "/home/hayer/itmat/benchmark_quantifiers/index/transcripts_offrate_1"
samtools: "/home/hayer/itmat/bp2/tools/samtools-0.1.19/samtools"
express: "/home/hayer/itmat/benchmark_quantifiers/tools/express-1.5.1-linux_x86_64/express"
kallisto: "/home/hayer/itmat/benchmark_quantifiers/tools/kallisto_linux-v0.42.3/kallisto"
kallisto_index: "/home/hayer/itmat/benchmark_quantifiers/index/transcripts_kallisto"
ireckon: "/home/hayer/itmat/benchmark_quantifiers/tools/IReckon-1.0.8.jar"
ireckon_ucsc: "/project/itmatlab/for_katharina/greg_new/annotation/mm9_ensebl_ucsc_format_filtered.txt"
